kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  annotations:
    app.openshift.io/vcs-ref: ''
    app.openshift.io/vcs-uri: 'https://github.com/purefield/ocp-virt.git'
    openshift.io/generated-by: OpenShiftWebConsole
  name: ocp-virt-git
  labels:
    app: ocp-virt-git
    app.kubernetes.io/component: ocp-virt-git
    app.kubernetes.io/instance: ocp-virt-git
    app.kubernetes.io/name: ocp-virt-git
    app.kubernetes.io/part-of: elastic-search-front-end
    app.openshift.io/runtime: nodejs
    app.openshift.io/runtime-version: 20-minimal-ubi8
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'ocp-virt-git:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'nodejs:20-minimal-ubi8'
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/purefield/ocp-virt.git'
    contextDir: /generate-data
  triggers:
    - type: Generic
      generic:
        secretReference:
          name: ocp-virt-git-generic-webhook-secret
    - type: GitHub
      github:
        secretReference:
          name: ocp-virt-git-github-webhook-secret
    - type: ImageChange
      imageChange: {}
    - type: ConfigChange
  runPolicy: Serial